apiVersion: v1
kind: Service
metadata:
  name: ats-app
  labels:
    app: ats-app
  namespace: ats-dev
spec:
  type: ClusterIP
  selector:
    app: ats-app
  ports:
  - name: ats-app-tcp-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ats-app
  namespace: ats-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ats-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ats-app
        application-name: ats-app
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - env:
          - name: TZ
            value: Asia/Bangkok
          envFrom: 
            - configMapRef:
                name: ats-app
          image: 393378649433.dkr.ecr.ap-southeast-1.amazonaws.com/protoss-technology/ats-app:latest
          imagePullPolicy: Always
          name: ats-app
          ports:
            - containerPort: 8000
              protocol: TCP
          # readinessProbe:
          #   initialDelaySeconds: 60
          #   httpGet:
          #     path: /api/v1/actuator/health
          #     port: 8000
          #     scheme: HTTP
          #   timeoutSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 8000
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 10
          #   periodSeconds: 20
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            limits:
              cpu: "256m"
              memory: "512Mi"
            requests:
              cpu: "256m"
              memory: "512Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30